<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="COMPND-DTP-204" ignored="6" name="Test(failed)" tests="1" failures="1" timestamp="2019-12-17T13:43:49 IST" time="65.666" errors="0">
  <testcase name="EBookPurchaseUser" time="46.549" classname="Script.UserProductPurchase">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 2, Size: 2">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at feature.taskfeature.EbookPurchaseVAlidUser(taskfeature.java:181)
at Script.UserProductPurchase.EBookPurchaseUser(UserProductPurchase.java:28)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- EBookPurchaseUser -->
  <testcase name="GuestUserProductPurchase" time="0.0" classname="Script.UserProductPurchase">
    <ignored/>
  </testcase> <!-- GuestUserProductPurchase -->
  <testcase name="GuestUserNotPurchaseEBook" time="0.0" classname="Script.UserProductPurchase">
    <ignored/>
  </testcase> <!-- GuestUserNotPurchaseEBook -->
  <testcase name="ApplyDiscountCoupon" time="0.0" classname="Script.UserProductPurchase">
    <ignored/>
  </testcase> <!-- ApplyDiscountCoupon -->
  <testcase name="validUserProductPurchase" time="0.0" classname="Script.UserProductPurchase">
    <ignored/>
  </testcase> <!-- validUserProductPurchase -->
  <testcase name="ForgetPassword" time="0.0" classname="Script.UserProductPurchase">
    <ignored/>
  </testcase> <!-- ForgetPassword -->
  <testcase name="AddtoCart" time="0.0" classname="Script.UserProductPurchase">
    <ignored/>
  </testcase> <!-- AddtoCart -->
</testsuite> <!-- Test(failed) -->
